---
title: "minitestでエラーメッセージを検証"
draft: false
tags: ["rails","minitest"]
private: false
slug: "ca10b1b5-76b1-4c89-868e-f0ee7f32be9c"
date: "2019-06-14T12:21:53+09:00"
lastmod: "2019-06-14T12:21:53+09:00"
keywords: ["rails","minitest","ベジプロ","プログ","プログラム"]
# headless: true
---

```
class FooTest < Minitest::Test
  def test_boo!
    # RuntimeErrorが発生することを検証
    e = assert_raises RuntimeError do
      Foo.boo! # <= boo!random-messages-continue...
    end

    # エラーメッセージを検証
    assert { e.message.start_with?("boo!") }
  end
end
```

> [Minitestで例外クラスとエラーメッセージを検証する方法 - Qiita](https://qiita.com/jnchito/items/0d8ab1cd33d5985f7743)
